In [22]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
import numpy as np

### 데이터 준비

- sklearn에 내장된 데이터인 iris 데이터를 이용

In [23]:
iris = load_iris()

iris_df = pd.DataFrame(iris.data, columns=iris.feature_names)
iris_df['species'] = iris.target_names[iris.target]

## 1.사이킷런의 OneHotEncoder 이용

In [41]:
#2차원 행렬로 변환
encoding_target = iris_df['species'].values.reshape(-1,1)

# OneHotEncoder 객체 생성 및 적용
encoder = OneHotEncoder()
onehot_encoded1 = encoder.fit_transform(encoding_target)

#인코딩 결과 확인
onehot_encoded1 = onehot_encoded1.toarray()
print(onehot_encoded1)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

In [38]:
# 기존 데이터프레임과 원핫 인코딩 결과를 합치기
temp = pd.DataFrame(onehot_encoded1, columns=iris.target_names)
iris_df_encoded1 = pd.concat([iris_df, temp], axis=1)

#결과 확인
display(iris_df_encoded1)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

       species  setosa  versicolor  virginica  
0       setosa     1.0         0.0        0.0  
1       setosa     1.0         0.0        0.0  
2       setosa     1.0         0.0        0.0  
3       setosa     1.0         0.0        0.0  
4       setosa     1.0         0.0        0.0  
..         ...     ...         ...        ...  
145  virginica     0.0         0.0        1.0  
146  virginica     0.0         0.0        1.0  
147  virginica     0.0         0.0        1.0  
148  virginica     0.0         0.0        1.0  
149  virginica     0.0         0.0        1.0  

[150 rows x 8 columns]

## 2. Pandas의 get_dummies 이용

In [40]:
# 'species' 열을 원핫 인코딩
onehot_encoded2 = pd.get_dummies(iris_df['species'])

#인코딩 결과 확인
print(onehot_encoded2)

     setosa  versicolor  virginica
0      True       False      False
1      True       False      False
2      True       False      False
3      True       False      False
4      True       False      False
..      ...         ...        ...
145   False       False       True
146   False       False       True
147   False       False       True
148   False       False       True
149   False       False       True

[150 rows x 3 columns]


In [26]:
# 기존 데이터프레임과 원핫 인코딩 결과를 합치기
iris_df_encoded2 = pd.concat([iris_df, onehot_encoded2], axis=1)

# 결과 확인
display(iris_df_encoded2)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

       species  setosa  versicolor  virginica  
0       setosa    True       False      False  
1       setosa    True       False      False  
2       setosa    True       False      False  
3       setosa    True       False      False  
4       setosa    True       False      False  
..         ...     ...         ...        ...  
145  virginica   False       False       True  
146  virginica   False       False       True  
147  virginica   False       False       True  
148  virginica   False       False       True  
149  virginica   False       False       True  

[150 rows x 8 columns]